// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities
{
    public partial class Account
    {
        public Account()
        {
            Employees = new HashSet<Employee>();
        }

        public int AccountId { get; set; }
        public string AccountName { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}