// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities
{
    public partial class Team
    {
        public int Id { get; set; }
        public string TeamName { get; set; }
        public string TechnologyName { get; set; }
    }
}